### PR TITLE
Fix/handlers tests

### PR DESCRIPTION
**Pull request by vgenev**
I wouldn't delete them totally atm, since they might be useful for handlers tests and are based on the API datamodels and might be useful for that purpose.

### CODE REVIEW

**Comment by vgenev** [comment]
@ggrg why?

**Comment by vgenev** [comment]
@ggrg oh, sorry I should add a .test to those I have restored. My bad. on it.

**Comment by vgenev** [comment]
its running now

**Comment by ggrg** [comment]
Coverage report on base develop branch:
```
=============================== Coverage summary ===============================
Statements   : 19.92% ( 144/723 )
Branches     : 17.25% ( 44/255 )
Functions    : 5.15% ( 5/97 )
Lines        : 20.64% ( 141/683 )
================================================================================

1..3
# tests 3
# pass  3

# ok
```

**Pull request closed without merging**
