### PR TITLE
feat: better settlement query filters

### PR DESCRIPTION
**Pull request by partiallyordered**
Enable much better queries for settlements, for example:
```
GET /settlements?accountId=1,2,3&state=PENDING_SETTLEMENT,PS_TRANSFERS_COMMITTED
```

### CODE REVIEW

**Comment by partiallyordered** [comment]
@elnyry-sam-k @mdebarros I'd appreciate any feedback on this in principle, when you have a moment

**Comment by elnyry-sam-k** [comment]
Also @mdebarros - please review when you get a chance..

**Comment by partiallyordered** [comment]
> Do the changes, for example number to string effect current implementations

The changes to the actual API should be backward compatible. Because these are URL query parameters rather than object fields, and fundamentally URL query parameters are strings anyway, the only difference should be in what validation is performed. For example, the API should change from, e.g.
```
GET /settlements?accountId=2
```
to
```
GET /settlements?accountId=1,2,3
```

> and if so will this be a breaking change?

I'll address this separately. As far as I can tell, the "multiple parameter" changes should be completely backwards-compatible. _But_ the default values for from/to dates will result in some queries succeeding where they would not previously have done. Specifically the following invalid request:
```
GET /settlements
```
which is not currently valid because a request without query parameters is not valid, would become valid, by virtue of the default values. Thinking a bit more about this, it might be better to simply allow queries with no filters and remove these default date values because
1. the user can query all settlements if they want to, by specifying the earliest possible date as a from date
2. having these default values means the db query always has additional clauses, which will decrease its efficiency
3. because the user is able to request all settlements, why make their job difficult if that's what they really want? let's just remove the requirement of having any filters at all (especially as this change to the API should enable them to make more targeted queries and reduce their need to request all settlements)

> Furthermore, a more naïve question: the change to the query params from the swagger - does this work with no additional implementation (than what's in the PR?)

I actually don't know; I'd be surprised if there isn't more to do, not least some actual meaningful tests. I thought I'd put this out there and get some feedback on the idea of it before putting a lot of effort into it.

**Comment by elnyry-sam-k** [comment]
Thanks for the response, Matt. please go ahead with this; like your idea about allowing queries without any filters in some cases..

**Comment by partiallyordered** [comment]
Removed default date filters; did not remove enforcement of minimum number of query parameters.

**Comment by partiallyordered** [comment]
> does this work with no additional implementation (than what's in the PR?)

Turns out: yes; nothing else required.

**Comment by elnyry-sam-k** [comment]
> > does this work with no additional implementation (than what's in the PR?)
> 
> Turns out: yes; nothing else required.

Excellent !

**Pull request closed without merging**
